{ pkgs }: {
	deps = [
   pkgs.python311Packages.jupyter-server-terminals
   pkgs.python311Packages.jupyterlab-git
   pkgs.python311Packages.jupyter-client
   pkgs.python310Packages.jupyter_server
   pkgs.python310Packages.jupyter-server-mathjax
   pkgs.python311Packages.jupyter-cache
   pkgs.python310Packages.jupyter-lsp
   pkgs.python310Packages.jupyter
   pkgs.python310Packages.jupyter-cache
   pkgs.emacsPackages.jupyter
   pkgs.python310Packages.jupyterlab-lsp
   pkgs.python311Packages.jupyter-ydoc
   pkgs.python311Packages.jupyter-ui-poll
   pkgs.python310Packages.jupyter-server-ydoc
   pkgs.python311Packages.jupyter-c-kernel
   pkgs.python311Packages.jupyter
   pkgs.python311Packages.jupyterlab_server
   pkgs.python310Packages.jupyterlab-widgets
   pkgs.python310Packages.jupyter_console
   pkgs.python311Packages.jupyter-server-fileid
   pkgs.python310Packages.jupyter_client
   pkgs.python311Packages.jupyter-lsp
   pkgs.python310Packages.jupyter-telemetry
   pkgs.python310Packages.jupyter-server
   pkgs.python311Packages.jupyterlab-lsp
   pkgs.python311Packages.jupyter_core
   pkgs.python310Packages.jupyterhub
   pkgs.python311Packages.jupyter_server
   pkgs.python310Packages.jupyter-server-terminals
   pkgs.haskellPackages.JuPyTer-notebook
   pkgs.haskellPackages.requirements
   pkgs.haskellPackages.fpco-api
   pkgs.lispPackages.prove
   pkgs.rPackages.NCA
   pkgs.haskellPackages.ihaskell-rlangqq
   pkgs.python311Packages.rjsmin
   pkgs.python311Packages.safetensors
   pkgs.rPackages.PLRModels
   pkgs.taktuk
   pkgs.StormLib
   pkgs.go-dependency-manager
   pkgs.linuxPackages_hardened.vendor-reset
   pkgs.perl534Packages.SyntaxKeywordJunction
   pkgs.cinnamon.muffin
   pkgs.gnomeExtensions.dash-to-dock
   pkgs.haskellPackages.highlighter2
   pkgs.haskellPackages.hs-gizapp
   pkgs.civetweb
   pkgs.gvm-tools
   pkgs.linuxPackages_5_15_hardened.nvidia_x11_beta_open
   pkgs.megacli
   pkgs.perlPackages.TestNeeds
   pkgs.python311Packages.typical
   pkgs.emacsPackages.reddigg
   pkgs.haskellPackages.patch
   pkgs.rPackages.LinkageMapView
   pkgs.xorg.fontbh75dpi
   pkgs.gnomeExtensions.argos
   pkgs.emacsPackages.company-dcd
   pkgs.haskellPackages.shadowsocks
		pkgs.jupyter
        pkgs.jq
        pkgs.python3
        pkgs.python3Packages.pip
        pkgs.python3Packages.pandas
        pkgs.python3Packages.numpy
	];
}